PROJECT_ABBOT_REQUEST = """
{{
    "counterId": {counter_id},
    "exportFormat": 4,
    "spssEncoding": 0,
    "dateFrom": null,
    "dateTo": null,
    "includeAll": false,
    "addNumericPublicId": false,
    "allowFullSizeStrings": true,
    "exportQuestionText": false,
    "exportLabelsInsteadValues": false,
    "exportLabelsAndCodeValues": true,
    "ignoreErrors": true,
    "exportHostAddress": false,
    "exportUserAgent": false,
    "exportInterviewDumpUrl": false,
    "exportInterviewResult": true,
    "exportContactData": true,
    "exportValidationComments": false,
    "exportValidationDetails": false,
    "includeTotalDurations": false,
    "exportEndedCreatedDifference": false,
    "exportContractorInfo": false,
    "convertMultiLineTextToSingleLine": true,
    "exportSpoofingDataFields": false,
    "exportMobileAppId": false,
    "exportDurationInMinutes": false,
    "exportQuestionsDuration": false,
    "exportUpdatedAt": false,
    "archiveSingleXlsxResultFile": false,
    "easyTabsIntegration": false
        }}
"""