PROJECTS_REQUEST = """
{{
  "counterId": {counter_id},
  "exportFormat": 2,
  "spssEncoding": 0,
  "dateFrom": "{date_from}",
  "dateTo": "{date_to}",
  "includeAll": false,
  "addNumericPublicId": false,
  "allowFullSizeStrings": false,
  "exportQuestionText": false,
  "exportLabelsInsteadValues": false,
  "exportLabelsAndCodeValues": false,
  "ignoreErrors": false,
  "exportHostAddress": false,
  "exportUserAgent": false,
  "exportInterviewDumpUrl": false,
  "exportInterviewResult": false,
  "exportContactData": false,
  "exportValidationComments": false,
  "exportValidationDetails": false,
  "includeTotalDurations": false,
  "exportEndedCreatedDifference": false,
  "exportContractorInfo": false,
  "convertMultiLineTextToSingleLine": false,
  "exportSpoofingDataFields": false,
  "exportMobileAppId": false,
  "exportDurationInMinutes": false,
  "exportQuestionsDuration": false,
  "exportUpdatedAt": false,
  "archiveSingleXlsxResultFile": true,
  "easyTabsIntegration": false,
  "exportCallTalkDuration": false,
  "callTalkDurationThresholdSec": null,
  "maxRowsInXlsxFile": null
}}
"""
